### ISSUE TITLE
Geocoder should ignore country 

### ISSUE THREAD

**Issue by haggaie** [lutzky/TransportDroidIL#10]
In some places the geocoder returns an address containing just a city and a country. This confuses the query provider. I think that the address line should be compared with a hardcoded ישראל, and removed if necessary.

**Comment by lutzky** [comment]
@haggaie, isn't this fixed in 632b14ddc5d0b278f2ba4be88d3144dd1faeaaf0?

**Comment by haggaie** [comment]
I think it is. I don't remember :)
