### ISSUE TITLE
Automatic location detection is triggered by display rotation

### ISSUE THREAD

**Issue by lutzky** [lutzky/TransportDroidIL#13]
If a manual location is set, automatic location detection should be halted until requested again. Rotating the screen triggers automatic detection, and should not.

Found by: Sergei M.

**Comment by haggaie** [comment]
This stack-overflow question [1] might be related.

[1] Activity restart on rotation Android - http://stackoverflow.com/questions/456211/activity-restart-on-rotation-android

**Comment by haggaie** [comment]
In one of the comments they recommend using onSaveInstanceState [1]. It seems like a good idea, although we might need to also move the Geolocation instance out of the Activity, for it to persists the orientation change. Maybe using an Application class.

[1] http://stackoverflow.com/questions/4096169/onsaveinstancestate-and-onrestoreinstancestate#4101501

**Comment by lutzky** [comment]
Closed in e9fe4e13bd251c41bbf4e7f4da9d22b480a6943e.
