### ISSUE TITLE
Interactive queries are shown as HTML

### ISSUE THREAD

**Issue by haggaie** [lutzky/TransportDroidIL#4]
When search for instance "מירושלים לתל אביב" the response allows the user to choose whether she wants "תחנה מרכזית" or "ארלוזרוב". These options are currently shown in HTML, and there is no way for the user to choose either of them.

**Comment by haggaie** [comment]
I started a branch to work on this issue: https://github.com/haggaie/TransportDroidIL/tree/interaction
I have a problem convincing the server to accept my session id though. Maybe you could have a look.

**Comment by lutzky** [comment]
Closed in 1.2 (6749bc0350)

**Comment by lutzky** [comment]
(and even unit tested!)
