### ISSUE TITLE
Submit button should be disabled while detecting location

### ISSUE THREAD

**Issue by lutzky** [lutzky/TransportDroidIL#8]

**Comment by haggaie** [comment]
This is one way to handle it. An alternative might be to show a popup telling the user that she has to wait for the location to be detected, after she presses the search button. If I'm not mistaken, this popup will show anyway if the query takes too much time. This way, the user won't have to wait for the location to be detected, press the button, and then wait again for the query results. She could just press the button, and wait for the whole process to complete.

What do you think?

**Comment by lutzky** [comment]
I don't get it. Why would the user want to have a notification pop up that he can't click the button, when we can just prevent him from clicking it?

**Comment by haggaie** [comment]
My thought was that when the user presses the search button, the popup will say something like 'Waiting for location detection'. Once the detection is complete the popup will change to the query text automatically, and then when the results arrive, the popup will close and the results appear.

**Comment by lutzky** [comment]
Well, this would be appropriate if the geocoding were better. Currently, for
the most part, I don't trust the geocoder to give a fully relevant answer,
and I need to tweak it beforehand.

On Sat, Aug 27, 2011 at 10:23 PM, haggaie <
reply@reply.github.com>wrote:

> My thought was that when the user presses the search button, the popup will
> say something like 'Waiting for location detection'. Once the detection is
> complete the popup will change to the query text automatically, and then
> when the results arrive, the popup will close and the results appear.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/lutzky/TransportDroidIL/issues/8#issuecomment-1921045

## 

"Any instrument is just a vehicle to express who you are and your
relationship to the world. No matter what level you’re doing it on, playing
music is an opportunity to give something to the world."
—Flea

Ohad Lutzky

**Comment by haggaie** [comment]
I guess you're right. Even when the geocoder works fine, the one on the other side of the query doesn't always work as well.

**Comment by lutzky** [comment]
Wouldn't it be awesome if we could just transmit lat/long?

**Comment by haggaie** [comment]
Yeah. You know, in the Omni-Express busses they have a speaker automatically announce the bus stops. They would need ti have their coordinates in order to do that, wouldn't they?
